name: CI Pipeline

on: [pull_request]
permissions:}
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 15
          cache: 'npm'
          cache-dependency-path: codebase/rdicidr-0.1.0/package-lock.json
      
      - name: Intall dependencies
        run: npm install
        working-directory: codebase/rdicidr-0.1.0

      - name: Linting (ESlint)
        run: npm run lint
        working-directory: codebase/rdicidr-0.1.0

      - name: Formatting (Prettier)
        run: npm run prettier
        working-directory: codebase/rdicidr-0.1.0

      - name: Run Tests
        run: CI=true npm run test
        working-directory: codebase/rdicidr-0.1.0

      - name: Build Application
        run: npm run build
        working-directory: codebase/rdicidr-0.1.0

      - name: Archive build folder
        run: tar -czf build-artifact.tar.gz -C codebase/rdicidr-0.1.0 build

      - name: Creating artifact
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.base_ref }}-lattest
          name: Build artifact for ${{ github.base_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.base_ref }}-lattest
          files: build-artifact.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
      